// Generated by scripts/sync-design-profiles.mjs. Edit the canonical source.
import { catalog } from './catalog.js';
import { lightThemes, darkThemes } from './themes.js';
import { mergeTheme, resolveColor } from './mergeTheme.js';
import type { DesignOverrides, ProtoConfig, Theme } from './types.js';

export type { DesignOverrides, ProtoConfig } from './types.js';
export const PROFILE_CAPABILITY = 1;
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value));
const plain = (value: unknown): value is Record<string, unknown> => value !== null && typeof value === 'object' && !Array.isArray(value) && [Object.prototype, null].includes(Object.getPrototypeOf(value));

function keys(value: unknown, allowed: string[], location: string): asserts value is Record<string, unknown> {
  if (!plain(value)) throw Error(`${location} must be an object.`);
  for (const key of Object.keys(value)) if (!allowed.includes(key)) throw Error(`Unsupported design field: ${location}.${key}`);
}
function number(value: unknown, min: number, max: number, location: string) {
  if (typeof value !== 'number' || !Number.isFinite(value) || value < min || value > max) throw Error(`Invalid design value: ${location} (${min}–${max}).`);
}
function color(value: unknown): void {
  if (plain(value)) {
    keys(value, ['light', 'dark'], 'color');
    if (typeof value.light !== 'string' || typeof value.dark !== 'string') throw Error('Provide both light and dark colors.');
    color(value.light); color(value.dark); return;
  }
  if (typeof value !== 'string' || !/^(#[\da-f]{3,4}|#[\da-f]{6}|#[\da-f]{8}|transparent|black|white|red|blue|green|gray|grey|orange|purple|pink|yellow)$/i.test(value)) {
    const match = typeof value === 'string' && value.match(/^rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})(?:\s*,\s*(0(?:\.\d+)?|1(?:\.0+)?))?\s*\)$/);
    if (!match || match.slice(1, 4).some(n => Number(n) > 255) || (value as string).startsWith('rgba') !== (match[4] !== undefined)) throw Error('Use a supported hex, rgb or rgba color.');
  }
}

export function validateOverrides(value: unknown): DesignOverrides {
  keys(value, ['theme', 'colorScheme', 'accentColor', 'tokens'], 'design');
  if (value.theme !== undefined && !['base', 'liquidGlass', 'materialYou'].includes(value.theme as string)) throw Error('Unknown material theme.');
  if (value.colorScheme !== undefined && !['light', 'dark', 'system'].includes(value.colorScheme as string)) throw Error('Unknown color scheme.');
  if (value.accentColor !== undefined) color(value.accentColor);
  if (value.tokens !== undefined) {
    keys(value.tokens, ['surface', 'text', 'border', 'blur', 'radius', 'space', 'typography'], 'tokens');
    const groups: Record<string, string[]> = {
      surface: ['primary', 'secondary', 'card', 'nav'], text: ['primary', 'secondary', 'tertiary', 'destructive'],
      border: ['default', 'strong'], blur: ['nav', 'card', 'modal'], radius: ['card', 'button', 'nav', 'modal'],
      space: ['xs', 'sm', 'md', 'lg', 'xl'], typography: ['title', 'headline', 'body', 'caption', 'label'],
    };
    for (const [group, entries] of Object.entries(value.tokens)) {
      keys(entries, groups[group]!, `tokens.${group}`);
      for (const [key, entry] of Object.entries(entries)) {
        const at = `tokens.${group}.${key}`;
        if (['surface', 'text', 'border'].includes(group)) color(entry);
        else if (group === 'typography') {
          keys(entry, ['fontSize', 'fontWeight', 'lineHeight', 'letterSpacing'], at);
          for (const [property, n] of Object.entries(entry)) {
            if (property === 'fontWeight') { if (!['400', '500', '600', '700', '800'].includes(n as string)) throw Error(`Invalid ${at}.fontWeight.`); }
            else if (property === 'fontSize') number(n, 11, 64, at);
            else if (property === 'lineHeight') number(n, 11, 100, at);
            else number(n, -2, 4, at);
          }
        } else number(entry, 0, group === 'space' ? 128 : 100, at);
      }
    }
  }
  return clone(value) as DesignOverrides;
}

function merge(a: Record<string, any>, b: Record<string, any>): Record<string, any> {
  const out = clone(a);
  for (const [key, value] of Object.entries(b)) {
    if (value === undefined) continue;
    out[key] = plain(value) && plain(out[key]) ? merge(out[key], value) : clone(value);
  }
  return out;
}
function changed(current: Record<string, any>, expected: Record<string, any>): Record<string, any> {
  const out: Record<string, any> = {};
  for (const [key, value] of Object.entries(current)) {
    if (value === undefined) continue;
    if (plain(value) && plain(expected[key])) {
      const diff = changed(value, expected[key]);
      if (Object.keys(diff).length) out[key] = diff;
    } else if (JSON.stringify(value) !== JSON.stringify(expected[key])) out[key] = value;
  }
  return out;
}
function owned(config: ProtoConfig): DesignOverrides {
  return Object.fromEntries(['theme', 'colorScheme', 'accentColor', 'tokens'].filter(k => (config as any)[k] !== undefined).map(k => [k, (config as any)[k]]));
}
function profileAt(selection: { id: string; version: string }) {
  const profile = catalog.find(p => p.id === selection.id && p.version === selection.version);
  if (!profile) throw Error(`Design profile/version unavailable: ${selection.id}@${selection.version}`);
  return profile;
}
export function listProfiles() { return clone(catalog); }

export function resolveDesign(config: ProtoConfig, isDark: boolean): { theme: Theme; accent: string } {
  const themes = isDark ? darkThemes : lightThemes;
  const theme = mergeTheme(themes[config.theme ?? 'liquidGlass'] ?? themes.liquidGlass, config.tokens, isDark);
  for (const [role, style] of Object.entries(theme.typography)) {
    if (style.lineHeight !== undefined && style.lineHeight < style.fontSize) throw Error(`Typography ${role}: line height must fit the font size.`);
  }
  return { theme, accent: resolveColor(config.accentColor ?? '#007AFF', isDark) };
}

export function applyProfile<T extends ProtoConfig>(existing: T, selection: { id: string; version: string }, requested: unknown = {}, preserveExisting = true) {
  const profile = profileAt(selection);
  const incoming = validateOverrides(requested);
  let overrides: DesignOverrides = {};
  if (preserveExisting) {
    if (existing.designProfile) {
      const previous = profileAt(existing.designProfile);
      const saved = validateOverrides(existing.designProfile.overrides);
      overrides = merge(saved, changed(owned(existing), owned(applyProfile({}, previous, saved, false))));
    } else overrides = validateOverrides(owned(existing));
  }
  overrides = validateOverrides(merge(overrides, incoming));
  const values = merge(profile.defaults, overrides) as DesignOverrides;
  const result = { ...clone(existing), ...values, designProfile: { id: profile.id, version: profile.version, overrides } };
  // Materialize all values, so catalog updates never restyle a saved project.
  const light = resolveDesign(result, false), dark = resolveDesign(result, true);
  const tokens: Record<string, any> = clone(light.theme);
  for (const group of ['surface', 'text', 'border'] as const) {
    for (const key of Object.keys(tokens[group])) tokens[group][key] = {
      light: (light.theme[group] as any)[key], dark: (dark.theme[group] as any)[key],
    };
  }
  return { ...result, tokens: tokens as NonNullable<ProtoConfig['tokens']> & { space: Theme['space']; radius: Theme['radius'] } };
}
