// Generated by scripts/sync-design-profiles.mjs. Edit the canonical source.
import type { Theme } from './types.js';
import { defaultTypography } from './typography.js';

export const base: Theme = {
  typography: defaultTypography,
  surface: {
    primary: '#FFFFFF',
    secondary: '#F2F2F7',
    card: '#FFFFFF',
    nav: '#FFFFFF',
  },
  text: {
    primary: '#000000',
    secondary: 'rgba(0, 0, 0, 0.6)',
    tertiary: 'rgba(0, 0, 0, 0.4)',
    destructive: '#D70015',
  },
  blur: {
    nav: 0,
    card: 0,
    modal: 0,
  },
  border: {
    default: 'rgba(0, 0, 0, 0.1)',
    strong: 'rgba(0, 0, 0, 0.2)',
  },
  radius: {
    card: 12,
    button: 10,
    nav: 0,
    modal: 24,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};

export const baseDark: Theme = {
  typography: defaultTypography,
  surface: {
    primary: '#000000',
    secondary: '#1C1C1E',
    card: '#1C1C1E',
    nav: '#000000',
  },
  text: {
    primary: '#FFFFFF',
    secondary: 'rgba(255, 255, 255, 0.6)',
    tertiary: 'rgba(255, 255, 255, 0.4)',
    destructive: '#FF453A',
  },
  blur: {
    nav: 0,
    card: 0,
    modal: 0,
  },
  border: {
    default: 'rgba(255, 255, 255, 0.15)',
    strong: 'rgba(255, 255, 255, 0.3)',
  },
  radius: {
    card: 12,
    button: 10,
    nav: 0,
    modal: 24,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};


export const liquidGlass: Theme = {
  typography: defaultTypography,
  surface: {
    primary: 'rgba(255, 255, 255, 0.72)',
    secondary: 'rgba(255, 255, 255, 0.48)',
    card: '#F2F2F7',
    nav: 'rgba(255, 255, 255, 0.82)',
  },
  text: {
    primary: '#000000',
    secondary: 'rgba(0, 0, 0, 0.5)',
    tertiary: 'rgba(0, 0, 0, 0.3)',
    destructive: '#FF3B30',
  },
  blur: {
    nav: 40,
    card: 20,
    modal: 60,
  },
  border: {
    default: 'rgba(0, 0, 0, 0.08)',
    strong: 'rgba(0, 0, 0, 0.16)',
  },
  radius: {
    card: 22,
    button: 14,
    nav: 0,
    modal: 44,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};

export const liquidGlassDark: Theme = {
  typography: defaultTypography,
  surface: {
    primary: 'rgba(28, 28, 30, 0.72)',
    secondary: 'rgba(28, 28, 30, 0.48)',
    card: '#1c1c1e',
    nav: 'rgba(28, 28, 30, 0.82)',
  },
  text: {
    primary: '#FFFFFF',
    secondary: 'rgba(255, 255, 255, 0.6)',
    tertiary: 'rgba(255, 255, 255, 0.4)',
    destructive: '#FF453A',
  },
  blur: {
    nav: 40,
    card: 20,
    modal: 60,
  },
  border: {
    default: 'rgba(255, 255, 255, 0.12)',
    strong: 'rgba(255, 255, 255, 0.24)',
  },
  radius: {
    card: 22,
    button: 14,
    nav: 0,
    modal: 44,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};


export const materialYou: Theme = {
  typography: defaultTypography,
  surface: {
    primary: '#FFFBFE',
    secondary: '#E6E1E5',
    card: '#F4EFF4',
    nav: '#FFFBFE',
  },
  text: {
    primary: '#1C1B1F',
    secondary: '#49454F',
    tertiary: '#79747E',
    destructive: '#B3261E',
  },
  blur: {
    nav: 0,
    card: 0,
    modal: 0,
  },
  border: {
    default: '#CAC4D0',
    strong: '#79747E',
  },
  radius: {
    card: 12,
    button: 20,
    nav: 0,
    modal: 28,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};

export const materialYouDark: Theme = {
  typography: defaultTypography,
  surface: {
    primary: '#1C1B1F',
    secondary: '#2B2930',
    card: '#211F26',
    nav: '#1C1B1F',
  },
  text: {
    primary: '#E6E1E5',
    secondary: '#CAC4D0',
    tertiary: '#938F99',
    destructive: '#F2B8B5',
  },
  blur: {
    nav: 0,
    card: 0,
    modal: 0,
  },
  border: {
    default: '#49454F',
    strong: '#938F99',
  },
  radius: {
    card: 12,
    button: 20,
    nav: 0,
    modal: 28,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};

export const lightThemes = { base, liquidGlass, materialYou };
export const darkThemes = { base: baseDark, liquidGlass: liquidGlassDark, materialYou: materialYouDark };
